# Generated by Django 4.0.4 on 2022-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('skill', models.CharField(max_length=155)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('google_plus', models.URLField()),
            ],
        ),
    ]
