# Generated by Django 4.0.4 on 2022-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='image',
            field=models.ImageField(default='assets/image/stuff-img-01.jpg', upload_to='image/stuff_profile'),
        ),
    ]
