# Generated by Django 4.0.4 on 2022-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_stuff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(default='image/stuff_profile/stuff-img-01.jpg', upload_to='image/stuff_profile'),
        ),
    ]
