# Generated by Django 4.0.4 on 2022-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_for_detail',
            field=models.ImageField(default='assets/images/inner-blog-img.jpg', upload_to='image/article_detail'),
        ),
    ]
