# Generated by Django 4.0.4 on 2022-05-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_image_for_detail_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
